"""
measurements/dc.py
==================
DC characterization for a 5-pin op-amp DUT (A+, A-, Aout, V+, V-).
STATUS: validated and finalized on OPA4388, 2026-07 (see "Known-good
results" below). Settling/artifact issues from earlier development are
resolved -- see "Development history" if you hit something that looks
like those symptoms again.

--------------------------------------------------------------------
PHYSICAL CONNECTIONS
--------------------------------------------------------------------
Power
    OPA4388 V+  -> 5.0V (bench supply or Keithley 2450)
    OPA4388 V-  -> AGND
    100nF ceramic + 10uF bulk decoupling right at the V+ pin.
    Sequencing: bring V+ up BEFORE any DAC output is commanded above
    0V; zero the DAC before removing V+. (Same rule as the USB
    hotplug/latch-up guidance elsewhere in this project -- an input
    signal present without its supply properly up can forward-bias
    input ESD/clamp diodes.)

Reference node (Vref = 2.5V)
    Generated by a dedicated ADR4525 reference chip (NOT a DAC
    channel -- do not rely on self.vref alone to make this voltage
    exist in hardware, it is a math constant used only to reconstruct
    Aout from the ADC's differential reading).
    ADR4525 output -> Rg (10k) -> op-amp A- pin
    ADR4525 output -> ADS131A04 AINN (this channel's negative input)

Feedback network (non-inverting, gain = 1 + Rf/Rg = 11 nominal)
    Rg = 10k   : op-amp A- pin  <-> Vref node (ADR4525 output)
    Rf = 100k  : op-amp A- pin  <-> op-amp Aout pin
    (Rg and Rf meet at the A- pin -- that junction is the feedback node.)

Input stimulus
    DAC80508 dac_num/dac_ch (default chip1/ch1, i.e. OUT0) -> A+ pin
    Driven via the NI USB-6212 bit-bang bus (hardware.dac_dac80508),
    NOT the STM32 -- this is a hybrid fixture: DAC on the NI path,
    ADC on the STM32/USB-CDC path, running simultaneously.

Output acquisition (differential, NOT single-ended)
    ADS131A04 AINP (adc_chip/adc_ch) -> op-amp Aout pin
    ADS131A04 AINN (same channel)    -> Vref node (ADR4525 output)
    The ADC channel therefore reports (Aout - Vref) natively; this
    script adds self.vref back to reconstruct the true Aout. This
    keeps the 0..5V single-ended swing inside the ADC's differential
    input range -- feeding Aout single-ended against ADC ground would
    clip the ADC on any output above a few volts.

Ground
    DAC80508 GND, ADS131A04 AVSS/DVSS, STM32 GND, and op-amp V- all
    tie to one common ground point near the ADC (star topology,
    not daisy-chained) -- noise here shows up directly as the
    baseline() noise-floor number.

Unused channels (OPA4388 is a quad package)
    Tie each unused channel's A+ and A- together, connected to the
    Vref node. Leave outputs floating (no load needed). This matters:
    an earlier OPA4197 on this same fixture died, most likely from an
    unused channel railing and stressing the shared V+/V- supply pins
    common to all four internal amplifiers on the die.

--------------------------------------------------------------------
KNOWN-GOOD RESULTS (OPA4388, this fixture, most recent clean run)
--------------------------------------------------------------------
    Gain            : 10.86  (nominal 11, -1.3% -- within resistor tolerance)
    Vos (fixture)   : -1.98 mV  (fixture/resistor-tolerance-limited;
                       chip's real spec is 0.25uV, far below what this
                       rig can resolve -- do not read this as chip Vos)
    INL             : 0.11%, asymmetric (steeper near the +rail) --
                       consistent with real rail-to-rail output-stage
                       compression, not an artifact
    Baseline noise  : ~250uV RMS at the output node

--------------------------------------------------------------------
DEVELOPMENT HISTORY (context for future maintainers)
--------------------------------------------------------------------
Earlier debugging on this fixture found, in order: a loose DAC SPI
daisy-chain connection (output pinned, DAC changes had no effect), a
dead OPA4197 (V- pin measured 4.xV despite being tied to AGND -- an
internal short, most likely from an untied unused channel), and after
swapping to OPA4388, a large decaying leading-edge artifact on the
first ~10 points of every sweep following a rail-to-linear transition
(coarse sweep's saturated tail -> fine sweep's first point). That
artifact was NOT the op-amp (datasheet: ~10us overload recovery, ~2us
settling -- both negligible) -- it was the ADS131A04's own decimation
filter needing real time/samples to flush stale data after a big step.
Fixed via _wait_for_stable(): after any reading near a rail, keep
pulling small ADC batches until several consecutive batch means agree,
rather than guessing a fixed sleep or flush count.

--------------------------------------------------------------------
Covers test sequence steps:
    0. Fixture baseline (no DUT / DUT input held at Vref) -> ADC noise floor
    1. Coarse sweep  -> operating range, clipping, rough gain
    2. Fine sweep+fit -> precise gain, Vos, INL/linearity error, output swing

Hardware bindings (matches your actual driver modules):
    hardware.dac_dac80508  -- module-level functions, NI USB-6212 bus
        initialize(), set_voltage(dac_num, ch_num, voltage), clear_all()
    hardware.ads131a04     -- ADS131 class, STM32 USB CDC bus
        read_buffered(chip, num_frames) -> (voltages[4,n], timestamps)

Usage:
    from measurements.dc import DCTest
    dc = DCTest(dac_num=1, dac_ch=1, adc_chip=1, adc_ch=1, tag="opa4388")
    dc.run_all()

1-indexed channel numbering throughout, matching the rest of the stack.
"""

import os
import csv
import json
import time
import numpy as np
import matplotlib.pyplot as plt

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

import sys
sys.path.insert(0, os.path.join(SCRIPT_DIR, ".."))

import hardware.dac_dac80508 as dacmod
from hardware.ads131a04 import ADS131


class DCTest:
    def __init__(self, dac_num=1, dac_ch=1, adc_chip=1, adc_ch=1,
                 vref=2.5, vpos=5.0, g_nom=11.0,
                 settle_s=0.005, n_avg=64, tag="opa4197",
                 adc: ADS131 = None):
        self.dac_num = dac_num      # DAC80508 chip 1-5
        self.dac_ch = dac_ch        # DAC80508 channel 1-8 (OUT0-OUT7)
        self.adc_chip = adc_chip    # ADS131A04 chip 1-2
        self.adc_ch = adc_ch        # ADS131A04 channel 1-4
        self.vref = vref
        self.vpos = vpos
        self.g_nom = g_nom
        self.settle_s = settle_s    # settle time after each DAC step
        self.n_avg = n_avg          # frames averaged per read point
        self.tag = tag
        self.results = {}
        self._last_aout = None   # tracks whether we're coming out of saturation

        # bring up the NI-based DAC bus once; auto-inits on first
        # set_voltage() too, but explicit here keeps timing predictable
        dacmod.initialize()

        # ADS131() opens the STM32 CDC port and pings the firmware;
        # reuse an existing instance if the caller already has one open
        # (only one CDC port can be open at a time)
        self.adc = adc if adc is not None else ADS131()

    def _dac_set(self, volts):
        """Command A+ input voltage via NI-bus DAC80508 driver."""
        dacmod.set_voltage(self.dac_num, self.dac_ch, volts)

    def _adc_read_n(self, n):
        """
        Return n samples of Aout (volts), reconstructed from the
        differential (Aout - Vref) reading.
        """
        v_arr, _t = self.adc.read_buffered(chip=self.adc_chip, num_frames=n)
        ch_row = v_arr[self.adc_ch - 1]        # index 0..3 for ch 1..4
        return ch_row + self.vref

    def _wait_for_stable(self, batch_n=100, tol_v=2e-5, window=5, max_batches=120):
        """
        Read repeated small batches, keeping a rolling window of the last
        `window` batch means. Only declare stable once that whole window's
        spread (max-min) is within tol_v -- a single lucky adjacent pair
        isn't a strong enough test, since a slow decay can produce small
        step-to-step differences well before it actually reaches its
        asymptote (this is what the previous version got wrong).
        """
        means, row = [], None
        for _ in range(max_batches):
            v_arr, _t = self.adc.read_buffered(chip=self.adc_chip, num_frames=batch_n)
            row = v_arr[self.adc_ch - 1]
            means.append(float(np.mean(row)))
            if len(means) >= window and (max(means[-window:]) - min(means[-window:])) < tol_v:
                return row
        return row  # gave up at max_batches -- still return the last batch

    def _measure_point(self, vin):
        """
        Set input, settle, return (Aout_mean, Aout_std).
        The OPA4388 itself settles in ~2us and recovers from overload in
        ~10us (datasheet spec) -- nowhere near the bottleneck. The lag
        after a big step is downstream of the amplifier (most likely the
        ADS131A04's decimation filter). Wait for the reading to actually
        stabilize after a rail transition rather than guessing a delay.
        """
        near_rail = (self._last_aout is not None and
                     (self._last_aout < 0.1 or self._last_aout > self.vpos - 0.1))
        self._dac_set(vin)
        time.sleep(self.settle_s)
        if near_rail:
            self._wait_for_stable()
        s = self._adc_read_n(self.n_avg)   # now record the real reading
        mean_v = float(np.mean(s))
        self._last_aout = mean_v
        return mean_v, float(np.std(s))

    # -- Step 0: baseline -----------------------------------------------------
    def baseline(self):
        """Hold input at Vref, capture ADC noise floor at the output node."""
        self._dac_set(self.vref)
        time.sleep(0.05)
        self._wait_for_stable()   # flush until the reading actually stabilizes
        s = self._adc_read_n(4096)
        noise_rms = float(np.std(s))
        self.results["baseline"] = {
            "aout_at_vref_mean": float(np.mean(s)),
            "noise_rms_V": noise_rms,
            "noise_rms_uV": noise_rms * 1e6,
            "n_samples": len(s),
        }
        print(f"[0] baseline: Aout(Vin=Vref)={np.mean(s):.6f}V  "
              f"noise_rms={noise_rms*1e6:.2f}uVrms")
        return self.results["baseline"]

    # -- Step 1: coarse sweep -------------------------------------------------
    def coarse_sweep(self, n=41):
        span = (self.vpos / 2.0) / self.g_nom
        vin = np.linspace(self.vref - span * 1.3, self.vref + span * 1.3, n)
        vin = np.clip(vin, 0.0, self.vpos)
        aout = np.array([self._measure_point(v)[0] for v in vin])

        lo_rail, hi_rail = 0.05, self.vpos - 0.05
        linear = (aout > lo_rail) & (aout < hi_rail)
        print(f"[1] coarse: Aout range over sweep = "
              f"{aout.min():.4f}V .. {aout.max():.4f}V  "
              f"(non-rail window is {lo_rail:.2f}V..{hi_rail:.2f}V)")
        if linear.sum() >= 2:
            g_rough = np.polyfit(vin[linear], aout[linear], 1)[0]
            vin_lin = (vin[linear].min(), vin[linear].max())
            vout_lin = (aout[linear].min(), aout[linear].max())
            print(f"[1] coarse: G~{g_rough:.3f}  Vin_linear={vin_lin}  "
                  f"Vout_swing={vout_lin}")
        else:
            g_rough, vin_lin, vout_lin = float("nan"), (None, None), (None, None)
            print("[1] coarse: WARNING -- every point fell outside the "
                  "non-rail window. Aout is saturated across the WHOLE "
                  "sweep, not just at the edges. Check the DC bias point "
                  "(Vin=Vref) directly -- see quick_check.py -- before "
                  "widening or re-running the sweep.")

        self.results["coarse"] = {
            "vin": vin.tolist(), "aout": aout.tolist(),
            "g_rough": g_rough,
            "vin_linear_range": vin_lin,
            "vout_swing": vout_lin,
            "vout_lo_rail_V": float(aout.min()),
            "vout_hi_rail_V": float(aout.max()),
        }
        return self.results["coarse"]

    # -- Step 2: fine sweep + fit --------------------------------------------
    def fine_sweep(self, n=101, guard=0.10):
        c = self.results.get("coarse")
        if not c or c["vin_linear_range"][0] is None:
            raise RuntimeError("run coarse_sweep() first (no linear region found)")

        v0, v1 = c["vin_linear_range"]
        pad = (v1 - v0) * guard
        vin = np.linspace(v0 + pad, v1 - pad, n)
        pts = [self._measure_point(v) for v in vin]
        aout = np.array([p[0] for p in pts])
        astd = np.array([p[1] for p in pts])

        G, b = np.polyfit(vin, aout, 1)

        aout_at_vref = G * self.vref + b
        vos = (aout_at_vref - self.vref) / G

        fit = G * vin + b
        resid = aout - fit
        span = aout.max() - aout.min()
        inl_pct = float(np.max(np.abs(resid)) / span * 100.0)

        self.results["fine"] = {
            "vin": vin.tolist(), "aout": aout.tolist(), "aout_std": astd.tolist(),
            "gain": float(G),
            "gain_nom": self.g_nom,
            "vos_V": float(vos),
            "vos_uV": float(vos * 1e6),
            "inl_max_pct": inl_pct,
            "inl_max_uV_out": float(np.max(np.abs(resid)) * 1e6),
            "resid_V": resid.tolist(),
        }
        print(f"[2] fine: G={G:.4f} (nom {self.g_nom})  "
              f"Vos={vos*1e6:.1f}uV  INL={inl_pct:.3f}% of span")
        return self.results["fine"]

    # -- orchestration + output ----------------------------------------------
    def run_all(self):
        self.baseline()
        self.coarse_sweep()
        try:
            self.fine_sweep()
        except Exception:
            self.save()   # keep baseline+coarse on disk even if this fails
            raise
        self.save()
        self.plot()
        return self.results

    def save(self):
        base = os.path.join(SCRIPT_DIR, f"dc_{self.tag}")
        with open(base + ".json", "w") as f:
            json.dump(self.results, f, indent=2)
        fine = self.results.get("fine")
        if fine:
            with open(base + "_fine.csv", "w", newline="") as f:
                w = csv.writer(f)
                w.writerow(["vin_V", "aout_V", "aout_std_V", "residual_V"])
                for row in zip(fine["vin"], fine["aout"],
                               fine["aout_std"], fine["resid_V"]):
                    w.writerow(row)
        print(f"    saved {base}.json / _fine.csv")

    def plot(self):
        fig, ax = plt.subplots(2, 1, figsize=(8, 8), sharex=False)
        c, fine = self.results.get("coarse"), self.results.get("fine")
        if c:
            ax[0].plot(c["vin"], c["aout"], ".-", label="coarse")
            ax[0].axhline(0.05, ls=":", c="r"); ax[0].axhline(self.vpos - 0.05, ls=":", c="r")
            ax[0].set(xlabel="Vin (V)", ylabel="Aout (V)",
                      title=f"{self.tag}  coarse sweep + swing limits")
            ax[0].legend()
        if fine:
            ax[1].plot(fine["vin"], np.array(fine["resid_V"]) * 1e6, ".-")
            ax[1].set(xlabel="Vin (V)", ylabel="linearity residual (uV out)",
                      title=f"G={fine['gain']:.3f}  Vos={fine['vos_uV']:.1f}uV  "
                            f"INL={fine['inl_max_pct']:.3f}%")
            ax[1].axhline(0, ls=":", c="k")
        fig.tight_layout()
        out = os.path.join(SCRIPT_DIR, f"dc_{self.tag}.png")
        fig.savefig(out, dpi=120)
        print(f"    saved {out}")


if __name__ == "__main__":
    dc = DCTest(dac_num=1, dac_ch=1, adc_chip=1, adc_ch=1, tag="opa4388")
    try:
        dc.run_all()
    finally:
        dacmod.clear_all()   # always zero outputs + close NI task, even on crash